// flow-typed signature: e4c892d51bc181fef3800625c4923a33
// flow-typed version: <<STUB>>/decoders_v1.14.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decoders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decoders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'decoders/array' {
  declare module.exports: any;
}

declare module 'decoders/boolean' {
  declare module.exports: any;
}

declare module 'decoders/constants' {
  declare module.exports: any;
}

declare module 'decoders/date' {
  declare module.exports: any;
}

declare module 'decoders/dispatch' {
  declare module.exports: any;
}

declare module 'decoders/either' {
  declare module.exports: any;
}

declare module 'decoders/fail' {
  declare module.exports: any;
}

declare module 'decoders/guard' {
  declare module.exports: any;
}

declare module 'decoders/instanceOf' {
  declare module.exports: any;
}

declare module 'decoders/mapping' {
  declare module.exports: any;
}

declare module 'decoders/number' {
  declare module.exports: any;
}

declare module 'decoders/object' {
  declare module.exports: any;
}

declare module 'decoders/optional' {
  declare module.exports: any;
}

declare module 'decoders/string' {
  declare module.exports: any;
}

declare module 'decoders/tuple' {
  declare module.exports: any;
}

declare module 'decoders/types' {
  declare module.exports: any;
}

declare module 'decoders/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'decoders/array.js' {
  declare module.exports: $Exports<'decoders/array'>;
}
declare module 'decoders/boolean.js' {
  declare module.exports: $Exports<'decoders/boolean'>;
}
declare module 'decoders/constants.js' {
  declare module.exports: $Exports<'decoders/constants'>;
}
declare module 'decoders/date.js' {
  declare module.exports: $Exports<'decoders/date'>;
}
declare module 'decoders/dispatch.js' {
  declare module.exports: $Exports<'decoders/dispatch'>;
}
declare module 'decoders/either.js' {
  declare module.exports: $Exports<'decoders/either'>;
}
declare module 'decoders/fail.js' {
  declare module.exports: $Exports<'decoders/fail'>;
}
declare module 'decoders/guard.js' {
  declare module.exports: $Exports<'decoders/guard'>;
}
declare module 'decoders/index' {
  declare module.exports: $Exports<'decoders'>;
}
declare module 'decoders/index.js' {
  declare module.exports: $Exports<'decoders'>;
}
declare module 'decoders/instanceOf.js' {
  declare module.exports: $Exports<'decoders/instanceOf'>;
}
declare module 'decoders/mapping.js' {
  declare module.exports: $Exports<'decoders/mapping'>;
}
declare module 'decoders/number.js' {
  declare module.exports: $Exports<'decoders/number'>;
}
declare module 'decoders/object.js' {
  declare module.exports: $Exports<'decoders/object'>;
}
declare module 'decoders/optional.js' {
  declare module.exports: $Exports<'decoders/optional'>;
}
declare module 'decoders/string.js' {
  declare module.exports: $Exports<'decoders/string'>;
}
declare module 'decoders/tuple.js' {
  declare module.exports: $Exports<'decoders/tuple'>;
}
declare module 'decoders/types.js' {
  declare module.exports: $Exports<'decoders/types'>;
}
declare module 'decoders/utils.js' {
  declare module.exports: $Exports<'decoders/utils'>;
}
