// flow-typed signature: 8f0aa3354291e6bccd9c978558fb41db
// flow-typed version: <<STUB>>/jsonp_v^0.2.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonp/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonp/index' {
  declare module.exports: $Exports<'jsonp'>;
}
declare module 'jsonp/index.js' {
  declare module.exports: $Exports<'jsonp'>;
}
declare module 'jsonp/test/basic.js' {
  declare module.exports: $Exports<'jsonp/test/basic'>;
}
